# Generated by Django 4.0.4 on 2022-05-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='relationship',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
    ]
